name: auto tests 5-th step
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: make install
        - run: make lint
        - run: make test
